plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
theme: jekyll-theme-slate
title: Zego Fleet API Documentation
description: 
show_downloads: false
google_analytics: